name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-26.04, ubuntu-26.04-arm, macos-26, macos-26-intel]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-26.05
      - run: nix-build default.nix
      - run: nix build .#meson-nix-test
      - run: nix flake check .
